/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.ocp.day18;

/**
 *
 * @author NO NAME
 */
public class LottoJFrame extends javax.swing.JFrame {

    /**
     * Creates new form Lotto
     */
    public LottoJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lotto_title = new javax.swing.JLabel();
        lotto_label = new javax.swing.JLabel();
        lotto_jButton = new javax.swing.JButton();
        lotto_Box = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("樂透");

        lotto_title.setFont(new java.awt.Font("微軟正黑體", 1, 24)); // NOI18N
        lotto_title.setForeground(new java.awt.Color(255, 0, 0));
        lotto_title.setText("樂透");

        lotto_label.setFont(new java.awt.Font("微軟正黑體", 0, 36)); // NOI18N
        lotto_label.setText("00 00 00 00 00 00");

        lotto_jButton.setFont(new java.awt.Font("微軟正黑體", 1, 20)); // NOI18N
        lotto_jButton.setText("編號");
        lotto_jButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lotto_jButtonActionPerformed(evt);
            }
        });

        lotto_Box.setFont(new java.awt.Font("新細明體", 0, 24)); // NOI18N
        lotto_Box.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "金彩539", "4星彩" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(74, Short.MAX_VALUE)
                .addComponent(lotto_title)
                .addGap(48, 48, 48)
                .addComponent(lotto_Box, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(lotto_jButton)
                .addGap(89, 89, 89))
            .addGroup(layout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addComponent(lotto_label)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lotto_jButton)
                    .addComponent(lotto_title)
                    .addComponent(lotto_Box, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addComponent(lotto_label)
                .addContainerGap(126, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lotto_jButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lotto_jButtonActionPerformed
        //System.out.println(lotto_Box.getSelectedIndex());
        //System.out.println(lotto_Box.getSelectedItem());
        int idx = lotto_Box.getSelectedIndex();
        switch(idx){
            case 0:
                //lotto_jLabel.setText(LottoService.get539().toString());
                lotto_label.setText(LottoService.get539().toString().replace('[', ' ').replace(']', ' ').trim());
                break;
            case 1:
                lotto_label.setText(LottoService.get4stars().toString());
                break;    
        }
    }//GEN-LAST:event_lotto_jButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LottoJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LottoJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LottoJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LottoJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LottoJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> lotto_Box;
    private javax.swing.JButton lotto_jButton;
    private javax.swing.JLabel lotto_label;
    private javax.swing.JLabel lotto_title;
    // End of variables declaration//GEN-END:variables
}
